In [3]:
import numpy as np

## Создание массивов
- 1-мерные массивы (вектор-строка)
- 2-мерные массивы (векор-столбец, матрица)

In [4]:
# 1-мерный массив (векор-строка)
np.array([10,20,30,40])

array([10, 20, 30, 40])

In [6]:
# 2-мерный массив

# вектор-столбец
np.array([[10], [20], [30]])

array([[10],
       [20],
       [30]])

In [8]:
# матрица 

list_0 = [
    [100, 200, 300], 
    [400, 500, 600]
]
np.array(list_0)

array([[100, 200, 300],
       [400, 500, 600]])

In [9]:
# типы данных массива

arr_0 = np.zeros((3,3))
arr_0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr_0.dtype

dtype('float64')

In [11]:
# конвертация типа данных массива

arr_0.astype("uint8")

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [20]:
list_1 = [i for i in range(1000)]

In [16]:
list_1[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
for idx, var in enumerate(list_1):
    list_1[idx] = var + 10
list_1[:10]

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [23]:
arr_1 = np.arange(1000)
arr_1[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr_1 += 10

arr_1[:10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])