In [1]:
import numpy as np

In [2]:
## Атрибуты

In [21]:
# вектор-строка
arr_0 = np.random.randint(-10, 10, size=15)
arr_0

array([-7,  2, -3,  3,  3,  3,  6, -5,  3,  2,  6,  6,  8, -8, -6])

In [22]:
# вектор-столбец
arr_1 = np.random.randint(-10, 10, size=(5, 1))
arr_1

array([[ -1],
       [ -1],
       [  0],
       [-10],
       [  5]])

In [23]:
arr_2 = np.random.rand(3, 5)
arr_2

array([[0.70398395, 0.78739011, 0.49637875, 0.62150704, 0.04645025],
       [0.96288076, 0.43758151, 0.11841279, 0.58816196, 0.56811077],
       [0.69894366, 0.13125319, 0.27842164, 0.87784351, 0.69393016]])

In [24]:
# форма массива
arr_0.shape

(15,)

In [26]:
arr_1.shape

(5, 1)

In [27]:
# тип данных
arr_0.dtype

dtype('int32')

In [28]:
arr_2.dtype

dtype('float64')

In [29]:
# мерность массива (кол-во измерений/осей массива)

In [30]:
arr_0.ndim

1

In [31]:
arr_1.ndim

2

In [32]:
# занимаемый объем памяти (в байтах)
arr_2.nbytes

120

In [33]:
arr_0.nbytes

60

In [34]:
arr_1.nbytes

20

In [35]:
# Методы

In [36]:
arr_2

array([[0.70398395, 0.78739011, 0.49637875, 0.62150704, 0.04645025],
       [0.96288076, 0.43758151, 0.11841279, 0.58816196, 0.56811077],
       [0.69894366, 0.13125319, 0.27842164, 0.87784351, 0.69393016]])

In [41]:
# конвертация типа данных массива
arr_2.astype('float16')

array([[0.704  , 0.7876 , 0.4963 , 0.6216 , 0.04645],
       [0.963  , 0.4375 , 0.1184 , 0.5884 , 0.568  ],
       [0.6987 , 0.1312 , 0.2783 , 0.878  , 0.694  ]], dtype=float16)

In [42]:
# транспонирование - поворот массива по диагонали

In [45]:
arr_2.transpose()

array([[0.70398395, 0.96288076, 0.69894366],
       [0.78739011, 0.43758151, 0.13125319],
       [0.49637875, 0.11841279, 0.27842164],
       [0.62150704, 0.58816196, 0.87784351],
       [0.04645025, 0.56811077, 0.69393016]])

In [48]:
a = arr_2.T

In [47]:
arr_2

array([[0.70398395, 0.78739011, 0.49637875, 0.62150704, 0.04645025],
       [0.96288076, 0.43758151, 0.11841279, 0.58816196, 0.56811077],
       [0.69894366, 0.13125319, 0.27842164, 0.87784351, 0.69393016]])

In [49]:
a

array([[0.70398395, 0.96288076, 0.69894366],
       [0.78739011, 0.43758151, 0.13125319],
       [0.49637875, 0.11841279, 0.27842164],
       [0.62150704, 0.58816196, 0.87784351],
       [0.04645025, 0.56811077, 0.69393016]])

In [50]:
arr_2.min()

0.04645024904244899

In [54]:
arr_2.max(axis=0)

array([0.96288076, 0.78739011, 0.49637875, 0.87784351, 0.69393016])

In [55]:
arr_2.max(axis=1)

array([0.78739011, 0.96288076, 0.87784351])

In [56]:
# среднее значение 
arr_2.mean()

0.5340833367133012

In [59]:
arr_1.mean()

-1.4

In [64]:
# индексы минимального и максимального значений
arr_1.argmin()

3

In [65]:
arr_0

array([-7,  2, -3,  3,  3,  3,  6, -5,  3,  2,  6,  6,  8, -8, -6])

In [67]:
arr_0.argmin()

13

In [68]:
arr_0.argmax()

12

In [58]:
# зерно ГПСЧ
np.random.seed(0)
np.random.randint(10, size=5)

array([5, 0, 3, 3, 7])

In [70]:
# сортировка значений массива
arr_0.sort()

In [71]:
arr_0

array([-8, -7, -6, -5, -3,  2,  2,  3,  3,  3,  3,  6,  6,  6,  8])

In [72]:
# переворот от сортированного массива
arr_0[::-1]

array([ 8,  6,  6,  6,  3,  3,  3,  3,  2,  2, -3, -5, -6, -7, -8])

In [76]:
arr_3 = np.random.randint(10, size=5)
arr_3

array([6, 7, 7, 8, 1])

In [77]:
arr_3[2:] = arr_3[2:][::-1]
arr_3

array([6, 7, 1, 8, 7])

## Индексация

In [78]:
arr_4 = np.random.randint(20, size=(3,4))
arr_4

array([[ 5, 13,  8,  9],
       [19, 16, 19,  5],
       [15, 15,  0, 18]])

In [79]:
# прямая индексация
arr_4[1]

array([19, 16, 19,  5])

In [80]:
# обратная индексация
arr_4[-1]

array([15, 15,  0, 18])

In [81]:
# извлечение значений 
# стандартный питоновский синтаксис
arr_4[-1][2]

0

In [82]:
# синтаксис нампи
arr_4[-1, 2]

0

In [83]:
# запись значения
arr_4[-1,2] = 100
arr_4

array([[  5,  13,   8,   9],
       [ 19,  16,  19,   5],
       [ 15,  15, 100,  18]])

# Срезы

In [84]:
# срез строк
arr_4[1:]

array([[ 19,  16,  19,   5],
       [ 15,  15, 100,  18]])

In [85]:
arr_4[0, 1:]

array([13,  8,  9])

In [86]:
# срез столбцов

In [88]:
arr_4[:, 2:]

array([[  8,   9],
       [ 19,   5],
       [100,  18]])

In [89]:
# срез строк и столбцов
arr_4[:2, 1:]

array([[13,  8,  9],
       [16, 19,  5]])

In [90]:
arr_4

array([[  5,  13,   8,   9],
       [ 19,  16,  19,   5],
       [ 15,  15, 100,  18]])

In [91]:
arr_5 = arr_4[:2, 1:]
arr_5

array([[13,  8,  9],
       [16, 19,  5]])

In [92]:
arr_5[0,0] = 10
arr_5

array([[10,  8,  9],
       [16, 19,  5]])

In [93]:
arr_4

array([[  5,  10,   8,   9],
       [ 19,  16,  19,   5],
       [ 15,  15, 100,  18]])

In [94]:
# копия массива на базе массива

In [95]:
arr_6 = arr_4[:2, 1:].copy()

In [96]:
arr_6

array([[10,  8,  9],
       [16, 19,  5]])

In [97]:
arr_6[0,0] = 15

In [98]:
arr_6

array([[15,  8,  9],
       [16, 19,  5]])

In [99]:
arr_5

array([[10,  8,  9],
       [16, 19,  5]])