In [1]:
import numpy as np

## Операции 

In [2]:
# 1-мерный массив

In [8]:
arr_0 = np.arange(1,11)

In [9]:
arr_0

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr_1 = np.arange(0,19,2)

In [14]:
arr_1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# поэлементное сложение 2-х массивов

# решение с применением стандартного питонского инструментария
def arr_sum(a, b):
    res = []
    idx = 0
    for val in a:
        res.append(val + b[idx])
        idx += 1
    return res


In [21]:
arr_sum(arr_0, arr_1)

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28]

In [22]:
%timeit arr_sum(arr_0, arr_1)

3.24 µs ± 10 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [23]:
# решение с применением numpy
arr_0 + arr_1

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [24]:
# поэлементное умножение 2-х массивов

In [25]:
arr_2 = np.arange(3*3)
arr_3 = arr_2.reshape((3,3))

In [26]:
arr_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
arr_4 = np.arange(9).reshape((3,3))
arr_4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr_3 * arr_4

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [29]:
# Точечное умножение

# скаоярное произведение
r_vector = np.arange(3)
t_vector =  np.arange(3).reshape((3,1))

In [30]:
r_vector, t_vector

(array([0, 1, 2]),
 array([[0],
        [1],
        [2]]))

In [31]:
r_vector @ t_vector

array([5])

In [33]:
# вектор на матрицу
matrix_0 = np.arange(3*2).reshape((3,2))
matrix_0

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
r_vector @ matrix_0

array([10, 13])

In [35]:
# матрица на матрицу

matrix_1 = np.arange(2*2).reshape((2,2))
matrix_2 = np.arange(2*2).reshape((2,2))

matrix_1, matrix_2

(array([[0, 1],
        [2, 3]]),
 array([[0, 1],
        [2, 3]]))

In [36]:
matrix_1 @ matrix_2

array([[ 2,  3],
       [ 6, 11]])

In [37]:
# логические операции
matrix_1, matrix_2

(array([[0, 1],
        [2, 3]]),
 array([[0, 1],
        [2, 3]]))

In [38]:
# поэлементное сравнение
matrix_1 != matrix_2

array([[False, False],
       [False, False]])

In [39]:
# сравнение массива с скалярным значением
matrix_1 < 2

array([[ True,  True],
       [False, False]])

In [40]:
# все ли значения массива больше 2-х?

np.all(matrix_2 > 2)

False

In [41]:
# есть ли хоть одно значение в массиве, которое больше 2?
np.any(matrix_2 > 2)

True

In [44]:
# маскирование
np.random.seed(0)
arr_5 = np.random.randint(10, size=5)
arr_5

array([5, 0, 3, 3, 7])

In [45]:
mask = arr_5 >= 5
mask

array([ True, False, False, False,  True])

In [46]:
arr_5[mask]

array([5, 7])

In [47]:
# побитовые операторы

In [48]:
arr_5[arr_5 != 3]

array([5, 0, 7])